Changes to eggdb and sample handling

diff --git a/EGgPLant/eggdb b/EGgPLant/eggdb
--- a/EGgPLant/eggdb
+++ b/EGgPLant/eggdb
@@ -23,9 +23,8 @@ echo "d Database Name - The name for the database. NOTE: Spaces are not accepted
 echo "h Help - Displays help readout"
 }
 
-### Proabably should check to ensure I've put the colons in the right spot here.
 #pass options
-while getopts ":g:o:q:f:r:a:c:d:h s" opt; do
+while getopts ":g:o:q:f:r:a:c:d:h" opt; do
         case $opt in
         g) gene="${OPTARG}"
         ;;
@@ -46,9 +45,6 @@ while getopts ":g:o:q:f:r:a:c:d:h s" opt; do
         h) usage
         exit
         ;;
-        s) cat /usr/bin/.EGS
-        exit
-        ;;
         \?) echo
         echo "Invalid Option"
         usage
@@ -60,45 +56,37 @@ done
 mkdir -p "$db"/
 
 #search for query from gene region and organism inputs
-
-### Feel free to tidy this up. I am not an indent hater, I am more of an indent pacifist.
-
 if [ ! $gene == "" ]
-then
+        then
+        esearch -db nucleotide -query "$gene[All Fields] AND $org [Organism]"|
+        efetch -format fasta \
+        > fasta.tmp || { echo "Failed to create database, please check prompt and try again"; exit 1; }
 
-esearch -db nucleotide -query "$gene[All Fields] AND $org [Organism]"|
-efetch -format fasta \
-> fasta.tmp
+        esearch -db nucleotide -query "$gene[All Fields] AND $org [Organism]" |
+        efetch -format docsum |
+        xtract -pattern DocumentSummary -element AccessionVersion \
+        > "$db"/"$db"acc.txt || { echo "Failed to create database, please check prompt and try again"; exit 1; }
 
-esearch -db nucleotide -query "$gene[All Fields] AND $org [Organism]" |
-efetch -format docsum |
-xtract -pattern DocumentSummary -element AccessionVersion \
-> "$db"/"$db"acc.txt
-
-esearch -db nucleotide -query "$gene[All Fields] AND $org [Organism]" |
-efetch -format docsum |
-xtract -pattern DocumentSummary -element TaxId \
-> "$db"/"$db"taxid.txt
+        esearch -db nucleotide -query "$gene[All Fields] AND $org [Organism]" |
+        efetch -format docsum |
+        xtract -pattern DocumentSummary -element TaxId \
+        > "$db"/"$db"taxid.txt || { echo "Failed to create database, please check prompt and try again"; exit 1; }
 
 else
-#search for query using NCBI's syntax
+        #search for query using NCBI's syntax
+        esearch -db nucleotide -query "$query" |
+        efetch -format fasta \
+        > fasta.tmp || { echo "Failed to create database, please check prompt and try again"; exit 1; }
 
-esearch -db nucleotide -query "$query" |
-efetch -format fasta \
-> fasta.tmp
+        esearch -db nucleotide -query "$query" |
+        efetch -format docsum |
+        xtract -pattern DocumentSummary -element AccessionVersion \
+        > "$db"/"$db"acc.txt || { echo "Failed to create database, please check prompt and try again"; exit 1; }
 
-esearch -db nucleotide -query "$query" |
-efetch -format docsum |
-xtract -pattern DocumentSummary -element AccessionVersion \
-> "$db"/"$db"acc.txt
-
-esearch -db nucleotide -query "$query" |
-efetch -format docsum |
-xtract -pattern DocumentSummary -element TaxId \
-> "$db"/"$db"taxid.txt
-
-### Do we need another else function here in case the user doesn't add any options that are required?
-### Would be like "else echo ERROR: No valid search query provided"?
+        esearch -db nucleotide -query "$query" |
+        efetch -format docsum |
+        xtract -pattern DocumentSummary -element TaxId \
+        > "$db"/"$db"taxid.txt || { echo "Failed to create database, please check prompt and try again"; exit 1; }
 fi
 
 #remove suffixes
@@ -109,28 +97,26 @@ awk '{print $1}' fasta.tmp > "$db"/"$db".fasta
 ### this is the case, where the appropriate code will be run accordingly. Otherwise, we can provide the cutadapt code in the manual and instruct the user to run it on their
 ### custom fasta file BEFORE running the eggdb command. I just don't want to include custom sequences by default due to the inconsistency of having/not having primers still there.
 if [ ! $fwd == "" ]
-then
+        then
+        # Reverse complement reverse primer
+        revc=$(echo "$rev" | tr 'ATCG' 'TAGC' | rev)
 
-# Reverse complement reverse primer
-revc=$(echo "$rev" | tr 'ATCG' 'TAGC' | rev)
-
-# Perform in silico PCR, trimming primers concurrently
-for i in "$db"/"$db".fasta; do cutadapt -a $fwd...$revc -O $aln --trimmed-only --action trim -j 0 -o $i.out $i; done
-
-mv "$db"/"$db".fasta.out "$db"/"$db".fasta
+        # Perform in silico PCR, trimming primers concurrently
+        for i in "$db"/"$db".fasta; do cutadapt -a $fwd...$revc -O $aln --trimmed-only --action trim -j 0 -o $i.out $i; done
+        mv "$db"/"$db".fasta.out "$db"/"$db".fasta
 fi
 
 #Combine Files
 paste "$db"/"$db"acc.txt "$db"/"$db"taxid.txt > "$db"/"$db"taxmap.txt
 
 if [ ! $custom == "" ]
-then
-sed -n '1~2p' $custom | sed 's/>//g;s/_/ /g' | taxonkit name2taxid | sed 's/ /_/g' >taxa.tmp
-cat "$db"/"$db".fasta $custom >fasta.tmp
-mv fasta.tmp "$db"/"$db".fasta
-cat "$db"/"$db"taxmap.txt taxa.tmp >taxmap.tmp
-mv taxmap.tmp "$db"/"$db"taxmap.txt
-rm taxa.tmp
+        then
+        sed -n '1~2p' $custom | sed 's/>//g;s/_/ /g' | taxonkit name2taxid | sed 's/ /_/g' >taxa.tmp
+        cat "$db"/"$db".fasta $custom >fasta.tmp
+        mv fasta.tmp "$db"/"$db".fasta
+        cat "$db"/"$db"taxmap.txt taxa.tmp >taxmap.tmp
+        mv taxmap.tmp "$db"/"$db"taxmap.txt
+        rm taxa.tmp
 fi
 
 #Make Blast DB
@@ -153,9 +139,9 @@ echo "This can also be added to your .bashrc"
         echo
         if [[ $REPLY =~ ^[Yy]$ ]]
         then
-        export export BLASTDB="$cwd"/"$db" >& /dev/null
-        echo "export BLASTDB="$cwd"/"$db"" >> $HOME/.bashrc
-        echo "Please restart the terminal"
+                export export BLASTDB="$cwd"/"$db" >& /dev/null
+                echo "export BLASTDB="$cwd"/"$db"" >> $HOME/.bashrc
+                echo "Please restart the terminal"
         elif [[ $REPLY =~ ^[Nn]$ ]]; then
                 echo "Please remember to add this to before running blastn each session"
         fi
